version: '2'
services:
  web:
    build: .
    depends_on:
      - db
    volumes:
      - .:/task_manager:cached
    ports:
      - 5050:3000
    volumes_from:
      - bundle_cache
    environment:
      BUNDLE_PATH: /bundle_cache
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      TRAVIS_JOB_ID: ${TRAVIS_JOB_ID}
      TRAVIS_BRANCH: ${TRAVIS_BRANCH}
  db:
    image: postgres:10.3-alpine
  bundle_cache:
    image: busybox
    volumes:
      - /bundle_cache

