FROM ruby:2.5

RUN apt-get update -yq \
    && apt-get install curl gnupg -yq \
    && curl -sL https://deb.nodesource.com/setup_10.x | bash \
    && apt-get install curl gnupg -yq \
    && apt-get install nodejs -yq \
    && npm install -g yarn

RUN mkdir -p /task_manager
WORKDIR /task_manager
COPY . /task_manager
RUN bundle install
RUN yarn install
RUN bundle exec rails assets:precompile
